### ISSUE TITLE
Clicking on Show Log displays raw HTML

### ISSUE THREAD

**Issue by michaelpb** [herman-rogers/GambuildrRoadmap#10]
![](http://i.imgur.com/W12PV4Bh.png)

Ubuntu 16.04, Mozilla Firefox 53.0.2

**Comment by herman-rogers** [comment]
Awesome - we're a bit swamped at the moment but we'll get to this in the next week or so. Thanks for posting!

**Comment by herman-rogers** [comment]
This has also been resolved in recent builds - please let us know if it comes back!
