### ISSUE TITLE
Godot 2.1 - Linux game build does not run

### ISSUE THREAD

**Issue by michaelpb** [herman-rogers/GambuildrRoadmap#11]
![](http://i.imgur.com/gnkgDemh.png)

Ubuntu 16.04

Repository in question: https://bitbucket.org/michaelb/ld38

**Comment by herman-rogers** [comment]
Thanks for posting the repo URL - I'll take a look at this and get back to you.

* Might be sometime tonight (GMT+1) as I don't have a Linux computer at work (the horrors).

**Comment by herman-rogers** [comment]
Ok I'm able to repro this, not sure what's going on but we'll check it out and update you asap.

Edit: On further investigation it appears that your files are contained inside a "game" subdirectory, our build system assumes the engine.cfg file to be in the root directory. We'll fix the system to change into the correct build folder regardless of structure.

**Comment by herman-rogers** [comment]
Ok this is fixed now - although your build still doesn't work (I've tried building it manually with editor with the same results).
