### ISSUE TITLE
UX: Illegible placeholder text

### ISSUE THREAD

**Issue by michaelpb** [herman-rogers/GambuildrRoadmap#9]
![](http://i.imgur.com/a5gbP6Bh.png)

Perhaps remove placeholder text (since it already has a label in most/all (?) cases and thus is redundant), or increase contrast.

Ubuntu 16.04, Mozilla Firefox 53.0.2

**Comment by herman-rogers** [comment]
We've fixed this and darkened it a bit to allow people to see it better.
